apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smp

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - cloudflared-secret.yaml
  - cloudflared-deployment.yaml
  - ingress.yaml
